[package.build.backend]
name = "pixi-build-ros"
version = "*"

[package.build.config]
extra-package-mappings = [
    # libgmock-dev is a debian package, not available in conda
    { "libgmock-dev" = { conda = ["gmock"]}}
]
